config/routes.rb
Rails.application.routes.draw do

  root 'queries#index'
  get '/search' => 'queries#show', as: 'submit_search'
  get '/queries/:id' => 'queries#show', as: 'queries'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @words = CapitolWordsWrapper.phrase("civil rights")
  end

end

app/controllers/queries_controller.rb
require 'capitol_words_wrapper'
require 'the_counted_wrapper'

class QueriesController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    
  end

  def search
    if params[:search].present?
      @phrase = params[:search]
    else
      render :index
    end
  end

  def show
    if params[:search].present?
      @phrase = params[:search]
    else
      @phrase = params["id"].gsub!(/[^0-9a-z]/i, ' ')
    end
    @year = "2015"
    @state = CapitolWordsWrapper::STATES
    @total_mentions = CapitolWordsWrapper.total_mentions(@phrase)
    @min_max_mentions = CapitolWordsWrapper.min_max(@phrase)
    @min_fatalities_phrase = TheCountedWrapper.state_fatalities(@min_max_mentions[0]["state"])
    @max_fatalities_phrase = TheCountedWrapper.state_fatalities(@min_max_mentions[1]["state"])
    @fatalities = TheCountedWrapper.total_fatalities(@year)
    @min_max_fatalities_state = TheCountedWrapper.min_max_fatalities
  end

end

app/controllers/query_controller.rb
require 'capitol_words_wrapper'
require 'the_counted_wrapper'

class QueryController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @phrase = "civil rights"
    @year = "2015"
    @words = CapitolWordsWrapper.phrase(@phrase)
    @fatalities = TheCountedWrapper.year(@year)
    @matched_fatalities = TheCountedWrapper.state(@state)
  end

  def search
    if params[:search]
      @phrase_search = CapitolWordsWrapper.phrase(params[:search])
    else
      @phrase_search = CapitolWordsWrapper.phrase("civil rights")
    end
  end

  def civil_rights
    @year = "2015"
    @phrase = "civil rights"
    @state = CapitolWordsWrapper::STATES
    @total_mentions = CapitolWordsWrapper.total_mentions(@phrase)
    @min_max_mentions = CapitolWordsWrapper.min_max(@phrase)
    @min_fatalities_phrase = TheCountedWrapper.state_fatalities(@min_max_mentions[0]["state"])
    @max_fatalities_phrase = TheCountedWrapper.state_fatalities(@min_max_mentions[1]["state"])
    @fatalities = TheCountedWrapper.total_fatalities(@year)
    @min_max_fatalities_state = TheCountedWrapper.min_max_fatalities
  end

  def blm
    @phrase = "black lives matter"
    @state = CapitolWordsWrapper::STATES
    @words = CapitolWordsWrapper.phrase(@phrase)
    @matched_fatalities = TheCountedWrapper.state(@state)
  end

  def police_brutality
    @phrase = "police_brutality"
    @state = CapitolWordsWrapper::STATES
    @words = CapitolWordsWrapper.phrase(@phrase)
    @matched_fatalities = TheCountedWrapper.state(@state)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>don't talk about the cops</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Slabo+13px' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
      <h1 class="home-page">don't talk about the cops</h1>
      <nav class="navbar navbar-inverse navbar-collapse">
        <%= link_to root_path do %>
          <h1 class="navbar-header navbar-brand">home</h1>
        <% end %>
        <%= link_to queries_path(:civil_rights) do %>
          <h1 class="navbar-header navbar-brand">see "civil rights"</h1>
        <% end %>
        <%= link_to queries_path(:black_lives_matter) do %>
          <h1 class="navbar-header navbar-brand">see "black lives matter"</h1>
        <% end %>
        <%= link_to queries_path(:police_brutality) do %>
          <h1 class="navbar-header navbar-brand">see "police brutality"</h1>
        <% end %>

        <div class="search-bar">
          <%= form_tag submit_search_path, :method => "get", class: 'input-group'  do %>
            <%= text_field_tag :search, params[:search], class: 'form-control' %>
            <span class="input-group-btn">
              <%= submit_tag "search", class: "btn btn-default" %>
            </span>
          <% end %>
        </div>

      </nav>
    </header>
    <section class="container">

    <%= yield %>
  </section>

</body>
</html>

app/views/queries/_query.html.erb
<h1> <%= @phrase %> - 2015 </h1>

<div class="data">
  <ul>
    <li>total mentions: <%= @total_mentions %></li>
    <li>state where <%= @phrase %> mentioned most: <%= @min_max_mentions[1]["state"] %>, <%= @min_max_mentions[1]["count"] %> times</li>
    <li>and least: <%= @min_max_mentions[0]["state"] %>, <%= @min_max_mentions[0]["count"] %> times</li>
  </ul>
</div>

<div class="data">
  <ul>
    <li>total fatalities: <%= @fatalities %></li>
    <li>state with most fatalities: <%= @min_max_fatalities_state[1]["state"] %>, <%= @min_max_fatalities_state[1]["count"] %> deaths </li>
    <li>and least: <%= @min_max_fatalities_state[0]["state"] %>, <%= @min_max_fatalities_state[0]["count"] %> deaths </li>
  </ul>
</div>

<div class="list">
  <h2 class="navbar-header navbar-brand">police-related fatalities in <%= @min_max_fatalities_state[1]["state"] %></h2>
  <ul>
    <% @max_fatalities_phrase.each do |row| %>
    <li>Name: <%= row[:name] %></li>
    <li>Age: <%= row[:age] %></li>
    <li>Sex: <%= row[:sex] %></li>
    <li>Race: <%= row[:race] %></li>
    <li>State: <%= row[:state] %></li>
    <li>Cause: <%= row[:cause] %></li><br>
    <% end %>
  </ul>
</div>

<div class="list">
  <h2 class="navbar-header navbar-brand">police-related fatalities in <%= @min_max_fatalities_state[0]["state"] %></h2>
  <ul>
    <% @min_fatalities_phrase.each do |row| %>
    <br><li>Name: <%= row[:name] %></li>
    <li>Age: <%= row[:age] %></li>
    <li>Sex: <%= row[:sex] %></li>
    <li>Race: <%= row[:race] %></li>
    <li>State: <%= row[:state] %></li>
    <li>Cause: <%= row[:cause] %></li><br>
    <% end %>
  </ul>
</div>

app/views/queries/show.html.erb
<%= render :partial => 'query', :locals => { :id => @phrase } %>

app/views/query/phrase.html.erb
  <h1>Searching for Words </h1>
  <%= @words.each do |row| %>
  <%= row["state"] %>
  <%= row["count"] %>
  <% end %>

  <h1>Police-related fatalities</h1>
  <%= @fatalities.each do |row| %>
  <%= row["name"] %>
  <%= row["age"] %>
  <% end %>